;(function($,window,undefined){'use strict';var $event=$.event,$special,resizeTimeout;$special=$event.special.debouncedresize={setup:function(){$(this).on("resize",$special.handler);},teardown:function(){$(this).off("resize",$special.handler);},handler:function(event,execAsap){var context=this,args=arguments,dispatch=function(){event.type="debouncedresize";$event.dispatch.apply(context,args);};if(resizeTimeout){clearTimeout(resizeTimeout);}
execAsap?dispatch():resizeTimeout=setTimeout(dispatch,$special.threshold);},threshold:150};var BLANK='data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==';$.fn.imagesLoaded=function(callback){var $this=this,deferred=$.isFunction($.Deferred)?$.Deferred():0,hasNotify=$.isFunction(deferred.notify),$images=$this.find('img').add($this.filter('img')),loaded=[],proper=[],broken=[];if($.isPlainObject(callback)){$.each(callback,function(key,value){if(key==='callback'){callback=value;}else if(deferred){deferred[key](value);}});}
function doneLoading(){var $proper=$(proper),$broken=$(broken);if(deferred){if(broken.length){deferred.reject($images,$proper,$broken);}else{deferred.resolve($images);}}
if($.isFunction(callback)){callback.call($this,$images,$proper,$broken);}}
function imgLoaded(img,isBroken){if(img.src===BLANK||$.inArray(img,loaded)!==-1){return;}
loaded.push(img);if(isBroken){broken.push(img);}else{proper.push(img);}
$.data(img,'imagesLoaded',{isBroken:isBroken,src:img.src});if(hasNotify){deferred.notifyWith($(img),[isBroken,$images,$(proper),$(broken)]);}
if($images.length===loaded.length){setTimeout(doneLoading);$images.unbind('.imagesLoaded');}}
if(!$images.length){doneLoading();}else{$images.bind('load.imagesLoaded error.imagesLoaded',function(event){imgLoaded(event.target,event.type==='error');}).each(function(i,el){var src=el.src;var cached=$.data(el,'imagesLoaded');if(cached&&cached.src===src){imgLoaded(el,cached.isBroken);return;}
if(el.complete&&el.naturalWidth!==undefined){imgLoaded(el,el.naturalWidth===0||el.naturalHeight===0);return;}
if(el.readyState||el.complete){el.src=BLANK;el.src=src;}});}
return deferred?deferred.promise($this):$this;};var $window=$(window),Modernizr=window.Modernizr;$.Stapel=function(options,element){this.el=$(element);this._init(options);};$.Stapel.defaults={gutter:40,pileAngles:2,pileAnimation:{openSpeed:400,openEasing:'ease-in-out',closeSpeed:400,closeEasing:'ease-in-out'},otherPileAnimation:{openSpeed:400,openEasing:'ease-in-out',closeSpeed:350,closeEasing:'ease-in-out'},delay:0,randomAngle:false,onLoad:function(){return false;},onBeforeOpen:function(pileName){return false;},onAfterOpen:function(pileName,totalItems){return false;},onBeforeClose:function(pileName){return false;},onAfterClose:function(pileName,totalItems){return false;}};$.Stapel.prototype={_init:function(options){this.options=$.extend(true,{},$.Stapel.defaults,options);this._config();var self=this;this.el.imagesLoaded(function(){self.options.onLoad();self._layout();self._initEvents();});},_config:function(){this.support=Modernizr.csstransitions;var transEndEventNames={'WebkitTransition':'webkitTransitionEnd','MozTransition':'transitionend','OTransition':'oTransitionEnd','msTransition':'MSTransitionEnd','transition':'transitionend'},transformNames={'WebkitTransform':'-webkit-transform','MozTransform':'-moz-transform','OTransform':'-o-transform','msTransform':'-ms-transform','transform':'transform'};if(this.support){this.transEndEventName=transEndEventNames[Modernizr.prefixed('transition')]+'.cbpFWSlider';this.transformName=transformNames[Modernizr.prefixed('transform')];}
this.spread=false;this.items=this.el.children('li').hide();this.close=$('#tp-close');},_getSize:function(){this.elWidth=this.el.outerWidth(true);},_initEvents:function(){var self=this;$window.on('debouncedresize.stapel',function(){self._resize();});this.items.on('click.stapel',function(){var $item=$(this);if(!self.spread&&$item.data('isPile')){self.spread=true;self.pileName=$item.data('pileName');self.options.onBeforeOpen(self.pileName);self._openPile();return false;}});},_layout:function(){this._piles();this.itemSize={width:this.items.outerWidth(true),height:this.items.outerHeight(true)};this.items.remove();this._setInitialStyle();this.el.css('min-width',this.itemSize.width+this.options.gutter);this._getSize();this._setItemsPosition();this.items=this.el.children('li').show();this.itemsCount=this.items.length;},_piles:function(){this.piles={};var pile,self=this,idx=0;this.items.each(function(){var $item=$(this),itemPile=$item.attr('data-pile')||'nopile-'+$item.index(),attr=itemPile.split(',');for(var i=0,total=attr.length;i<total;++i){var pileName=$.trim(attr[i]);pile=self.piles[pileName];if(!pile){pile=self.piles[pileName]={elements:[],position:{left:0,top:0},index:idx};++idx;}
var clone=$item.clone().get(0);pile.elements.push({el:clone,finalPosition:{left:0,top:0}});$(clone).appendTo(self.el);}});},_setInitialStyle:function(){for(var pile in this.piles){var p=this.piles[pile];for(var i=0,len=p.elements.length;i<len;++i){var $el=$(p.elements[i].el),styleCSS={transform:'rotate(0deg)'};this._applyInitialTransition($el);if(i===len-2){styleCSS={transform:'rotate('+this.options.pileAngles+'deg)'};}
else if(i===len-3){styleCSS={transform:'rotate(-'+this.options.pileAngles+'deg)'};}
else if(i!==len-1){var extraStyle={visibility:'hidden'};$el.css(extraStyle).data('extraStyle',extraStyle);}
else if(pile.substr(0,6)!=='nopile'){$el.data('front',true).append('<div class="tp-title"><span>'+pile+'</span><span>'+len+'</span></div>');}
$el.css(styleCSS).data({initialStyle:styleCSS,pileName:pile,pileCount:len,shadow:$el.css('box-shadow'),isPile:pile.substr(0,6)==='nopile'?false:true});}}},_applyInitialTransition:function($el){if(this.support){$el.css('transition','left 400ms ease-in-out, top 400ms ease-in-out');}},_setItemsPosition:function(){var accumL=0,accumT=0,l,t,ml=0,lastItemTop=0;for(var pile in this.piles){var p=this.piles[pile],stepW=this.itemSize.width+this.options.gutter,accumIL=0,accumIT=0,il,it;if(accumL+stepW<=this.elWidth){l=accumL;t=accumT;accumL+=stepW;}
else{if(ml===0){ml=Math.ceil((this.elWidth-accumL+this.options.gutter)/ 2);}
accumT+=this.itemSize.height+this.options.gutter;l=0;t=accumT;accumL=stepW;}
p.position.left=l;p.position.top=t;for(var i=0,len=p.elements.length;i<len;++i){var elem=p.elements[i],fp=elem.finalPosition;if(accumIL+stepW<=this.elWidth){il=accumIL;it=accumIT;accumIL+=stepW;}
else{accumIT+=this.itemSize.height+this.options.gutter;il=0;it=accumIT;accumIL=stepW;}
fp.left=il;fp.top=it;var $el=$(elem.el);if(pile!==this.pileName){$el.css({left:p.position.left,top:p.position.top});}
else{lastItemTop=elem.finalPosition.top;$el.css({left:elem.finalPosition.left,top:lastItemTop});}}}
lastItemTop=this.spread?lastItemTop:accumT;this.el.css({marginLeft:ml,height:lastItemTop+this.itemSize.height});},_openPile:function(){if(!this.spread){return false;}
var fs;for(var pile in this.piles){var p=this.piles[pile],cnt=0;for(var i=0,len=p.elements.length;i<len;++i){var elem=p.elements[i],$item=$(elem.el),$img=$item.find('img'),styleCSS=pile===this.pileName?{zIndex:9999,visibility:'visible',transition:this.support?'left '+this.options.pileAnimation.openSpeed+'ms '+((len-i-1)*this.options.delay)+'ms '+this.options.pileAnimation.openEasing+', top '+this.options.pileAnimation.openSpeed+'ms '+((len-i-1)*this.options.delay)+'ms '+this.options.pileAnimation.openEasing+', '+this.transformName+' '+this.options.pileAnimation.openSpeed+'ms '+((len-i-1)*this.options.delay)+'ms '+this.options.pileAnimation.openEasing:'none'}:{zIndex:1,transition:this.support?'opacity '+this.options.otherPileAnimation.closeSpeed+'ms '+this.options.otherPileAnimation.closeEasing:'none'};if(pile===this.pileName){if($item.data('front')){$item.find('div.tp-title').hide();}
if(i<len-1){$img.css('visibility','visible');}
fs=elem.finalPosition;fs.transform=this.options.randomAngle&&i!==p.index?'rotate('+Math.floor(Math.random()*(5+5+1)-5)+'deg)':'none';if(!this.support){$item.css('transform','none');}
if(i<len-3){$item.css('box-shadow','none');}}
else if(i<len-1){$img.css('visibility','hidden');}
$item.css(styleCSS);var self=this;pile===this.pileName?this._applyTransition($item,fs,this.options.pileAnimation.openSpeed,function(evt){var target=this.target||this.nodeName;if(target!=='LI'){return;}
var $el=$(this);$el.css('box-shadow',$el.data('shadow'));if(self.support){$el.off(self.transEndEventName);}
++cnt;if(cnt===$el.data('pileCount')){$(document).one('mousemove.stapel',function(){self.el.addClass('tp-open');});self.options.onAfterOpen(self.pileName,cnt);}}):this._applyTransition($item,{opacity:0},this.options.otherPileAnimation.closeSpeed);}}
this.el.css('height',fs.top+this.itemSize.height);},_closePile:function(){var self=this;if(this.spread){this.spread=false;this.options.onBeforeClose(this.pileName);this.el.removeClass('tp-open');var fs;for(var pile in this.piles){var p=this.piles[pile],cnt=0;for(var i=0,len=p.elements.length;i<len;++i){var $item=$(p.elements[i].el),styleCSS=pile===this.pileName?{transition:this.support?'left '+this.options.pileAnimation.closeSpeed+'ms '+this.options.pileAnimation.closeEasing+', top '+this.options.pileAnimation.closeSpeed+'ms '+this.options.pileAnimation.closeEasing+', '+this.transformName+' '+this.options.pileAnimation.closeSpeed+'ms '+this.options.pileAnimation.closeEasing:'none'}:{transition:this.support?'opacity '+this.options.otherPileAnimation.openSpeed+'ms '+this.options.otherPileAnimation.openEasing:'none'};$item.css(styleCSS);fs=p.position;if(pile===this.pileName){$.extend(fs,$item.data('initialStyle'));if(i<len-3){$item.css('box-shadow','none');}}
pile===this.pileName?this._applyTransition($item,fs,this.options.pileAnimation.closeSpeed,function(evt){var target=this.target||this.nodeName;if(target!=='LI'){return;}
var $el=$(this),extraStyle=$el.data('extraStyle');$el.css('box-shadow',$el.data('shadow'));if(self.support){$el.off(self.transEndEventName);self._applyInitialTransition($el);}
else{$el.css($el.data('initialStyle'));}
if(extraStyle){$el.css(extraStyle);}
++cnt;if($el.data('front')){$el.find('div.tp-title').show();}
if(cnt===$el.data('pileCount')){self.options.onAfterClose($el.data('pileName'),cnt);}}):this._applyTransition($item,{opacity:1},this.options.otherPileAnimation.openSpeed,function(evt){var target=this.target||this.nodeName;if(target!=='LI'){return;}
var $el=$(this);if($el.index()<len-1){$el.find('img').css('visibility','visible');}
if(self.support){$el.off(self.transEndEventName);self._applyInitialTransition($el);}});}}
this.pileName='';this.el.css('height',fs.top+this.itemSize.height);}
return false;},_resize:function(){this._getSize();this._setItemsPosition();},_applyTransition:function(el,styleCSS,speed,fncomplete){$.fn.applyStyle=this.support?$.fn.css:$.fn.animate;if(fncomplete&&this.support){el.on(this.transEndEventName,fncomplete);}
fncomplete=fncomplete||function(){return false;};el.stop().applyStyle(styleCSS,$.extend(true,[],{duration:speed+'ms',complete:fncomplete}));},closePile:function(){this._closePile();}};var logError=function(message){if(window.console){window.console.error(message);}};$.fn.stapel=function(options){var instance=$.data(this,'stapel');if(typeof options==='string'){var args=Array.prototype.slice.call(arguments,1);this.each(function(){if(!instance){logError("cannot call methods on stapel prior to initialization; "+"attempted to call method '"+options+"'");return;}
if(!$.isFunction(instance[options])||options.charAt(0)==="_"){logError("no such method '"+options+"' for stapel instance");return;}
instance[options].apply(instance,args);});}
else{this.each(function(){if(instance){instance._init();}
else{instance=$.data(this,'stapel',new $.Stapel(options,this));}});}
return instance;};})(jQuery,window);